package classi;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import gestioneAccount.Amministratore;
import gestioneAcquisti.ordine;

public class TestOrdine {
	@Test
	   public void getId() {
	 ordine o = new ordine(1,60.00,"Pagato","RSSNNM00B19A509K");
	
	    assertEquals(1, o.getautoGeneratedID());
	  }
	
	@Test
	   public void setId() {
	 ordine o = new ordine();
	o.setautoGeneratedID(2);
	    assertEquals(2, o.getautoGeneratedID());
	  }
	@Test
	   public void getTotale() {
	 ordine o = new ordine(1,60.00,"Pagato","RSSNNM00B19A509K");
	
	assertEquals(60.00, o.getTotale(), 0);
	    
	  }
	
	@Test
	   public void setTotale() {
	 ordine o = new ordine();
	 o.setTotale(80.00);
		assertEquals(80.00, o.getTotale(), 0);
	  }
	
	@Test
	   public void getStato() {
	 ordine o = new ordine(1,60.00,"Pagato","RSSNNM00B19A509K");
	
	    assertEquals("Pagato", o.getStato());
	  }
	
	@Test
	   public void setStato() {
	 ordine o = new ordine();
o.setStato("Non_Pagato");
	    assertEquals("Non_Pagato", o.getStato());
	  }
	
	@Test
	   public void getCodice_fiscale() {
	 ordine o = new ordine(1,60.00,"Pagato","RSSNNM00B19A509K");
	
	    assertEquals("RSSNNM00B19A509K", o.getCodice_fiscale());
	  }
	
	@Test
	   public void setCodice_fiscale() {
	 ordine o = new ordine();
o.setCodice_fiscale("GSSNNM00B19A509P");
	    assertEquals("GSSNNM00B19A509P", o.getCodice_fiscale());
	  }
}
