package gestioneAcquisti;

import java.util.Date;

public class ordine {

	int autoGeneratedID;
	double totale;
	String stato;


	String codice_fiscale;
	
		public ordine() {		
			codice_fiscale="";
			
		}

	
		public ordine(int autoGeneratedID, double totale, String stato, String codice_fiscale) {
			super();
			this.autoGeneratedID = autoGeneratedID;
			this.totale = totale;
			this.stato = stato;
			this.codice_fiscale = codice_fiscale;
		}


		public int getautoGeneratedID() {
			return autoGeneratedID;
		}

		public void setautoGeneratedID(int autoGeneratedID) {
			this.autoGeneratedID = autoGeneratedID;
		}

		public String getCodice_fiscale() {
			return codice_fiscale;
		}

		public void setCodice_fiscale(String codice_fiscale) {
			this.codice_fiscale = codice_fiscale;
		}
		public double getTotale() {
			return totale;
		}


		public void setTotale(double totale) {
			this.totale = totale;
		}


		public String getStato() {
			return stato;
		}


		public void setStato(String stato) {
			this.stato = stato;
		}
}
