package gestioneAcquisti;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import GestioneCarrello.composto;
import GestioneCarrello.compostoModel;
import GestioneProdotti.ProductModelDS;
import GestioneProdotti.prodotto;
import gestioneAccount.LoginModelDS;
import gestioneAccount.Utente;
import Database.DBConnectionPool;

/**
 * Servlet implementation class ordiniclienti
 */
@WebServlet("/ordiniclienti")
public class ordiniclienti extends HttpServlet {
	private static final long serialVersionUID = 1L;
 
   
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	
		response.setContentType("text/html");
		String nomenegozio=(String) request.getSession().getAttribute("nome");

		Connection ds = null;
		try {
			ds = DBConnectionPool.getConnection();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		compostoModel modelcomposto=new compostoModel(ds);
		OrdineModel modelordine= new OrdineModel(ds);
		LoginModelDS modelnegozio=new LoginModelDS(ds);
		ProductModelDS prodotto=new ProductModelDS(ds);
		
		Utente neg=new Utente();
		prodotto p= new prodotto();
		
		StringBuffer risposta=new StringBuffer();
	
				Collection <ordine> ordine= new LinkedList<ordine>(); 
				Collection <composto> composto= new LinkedList<composto>(); 

				
			try {
				neg=modelnegozio.doRetrieveByNome(nomenegozio);
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		

			try {
				ordine=modelordine.doRetrieveByCodice_fiscale(neg.getCodice_fiscale());
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			risposta.append("<p>");
			risposta.append(neg.getNome());	
			risposta.append("</p>");
	
		Iterator<?> it=ordine.iterator();
		while(it.hasNext()) {
			ordine beans=(ordine) it.next();
				risposta.append("<p>");	
				risposta.append("N°Ordine :");
				risposta.append(beans.getautoGeneratedID());
				risposta.append(" ");
				risposta.append("</p>");
		
				try {
					composto=modelcomposto.doRetrieveByPiva(beans.getautoGeneratedID());
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
				Iterator <?> itcomposto=composto.iterator();
				while(itcomposto.hasNext()) {
					composto bean=(composto) itcomposto.next();
					
					try {
						p=prodotto.doRetrieveBySSN(bean.getSsn());
					} catch (SQLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					risposta.append("<p>");						
					risposta.append("Prodotto: ");
					risposta.append(p.getNome());
					risposta.append("     ");
					risposta.append("Pz:");
					risposta.append(bean.getQuantita());					
					risposta.append("</p>");
					
			
				}
		
		}

				
				
				
				
			
	
			
			
			
			
			
	
		
	
		
		
		response.getWriter().write(risposta.toString());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
