package seleniumtesting;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrazioneCorretta() {
    driver.get("http://localhost:8080/AgriShop/offerta");
    driver.manage().window().setSize(new Dimension(1261, 1032));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.cssSelector("#testocarrello > #bottone")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("mariorossi@libero.it");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("marioros");
    driver.findElement(By.id("conferma")).click();
    driver.findElement(By.id("conferma")).sendKeys("marioros");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Mario");
    driver.findElement(By.id("cognome")).click();
    driver.findElement(By.id("cognome")).sendKeys("Rossi");
    driver.findElement(By.id("codice_fiscale")).click();
    driver.findElement(By.id("codice_fiscale")).sendKeys("mmrraa090a203O");
    driver.findElement(By.id("indirizzo")).click();
    driver.findElement(By.id("indirizzo")).sendKeys("via roma");
    driver.findElement(By.id("civco")).click();
    driver.findElement(By.id("civco")).sendKeys("2");
    driver.findElement(By.id("cap")).click();
    driver.findElement(By.id("cap")).sendKeys("84084");
    driver.findElement(By.id("iscriviti")).click();
  }
  @Test
  public void registrazioneConPasswordMinoreDi8() {
    driver.get("http://localhost:8080/AgriShop/offerta");
    driver.manage().window().setSize(new Dimension(1261, 1032));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.cssSelector("#testocarrello > #bottone")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("michelerusso@libero.it");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("qqqq");
    driver.findElement(By.id("conferma")).click();
    driver.findElement(By.id("conferma")).click();
    driver.findElement(By.id("password")).sendKeys("qqqqqq");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("iscriviti")).click();
    driver.findElement(By.id("iscriviti")).click();
    driver.findElement(By.id("iscriviti")).click();
  }
}
